<?php
/**
 * @file
 * Code for the GSB Feature Business Insight Display feature.
 */

include_once 'gsb_feature_business_insight_display.features.inc';

function gsb_feature_business_insight_display_entity_info_alter(&$entity_info) {
  
  $entity_info['node']['view modes']['tiny'] = array(
    'label' => t('Tiny display'),
    'custom settings' => TRUE,
  );

  $entity_info['field_collection_item']['view modes']['tiny'] = array(
    'label' => t('Tiny display'),
    'custom settings' => TRUE,
  );

}
